version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible
      - run: pip3 install boto
      - run: pip3 install boto3
      - add_ssh_keys:
         fingerprints:
          - "70:bd:a9:a9:5c:45:82:c9:00:87:14:a1:a0:53:06:1d"
      - run: echo $SECRET_KEY test.pem
      - run: chmod 400 test.pem
      - run: echo $HESLO_ANSIBLE > .heslo_ansible.txt
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master